# import

In [213]:
import os
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import numpy.matlib
from pathlib import Path
from scipy import constants
from scipy.linalg import block_diag

# 芯片参数设计

## 基本参数
电容单位为fF

In [188]:
# C_q表示比特自电容，外层index表示周围有几个coupler1、2、3、4,内层表示每个岛的子电容，最后一项表示岛间电容
C_q = np.array([[80]*2+[9], [80]*2+[9], [80]*2+[9], [80]*2+[9]])
# C_c表示coupler自电容，外层index表示coupler类型，内层表示每个岛的子电容，最后一项表示岛间电容
C_c = np.array([[90]*2+[8], [90]*2+[8]])
# C_qc表示qc耦合电容，最外层表示coupler类型，中层表示比特的每个岛，内层表示对coupler的每个岛的电容
C_qc = np.array([[[5, 5], [5, 5]], [[5, 5], [5, 5]]])
# C_qc表示qq耦合电容，外层表示第一个比特的岛，内层表示第二个比特的岛
C_qq = np.array([[0.5, 0.5], [0.5, 0.5]])
# n_q为每行的比特个数
shape_q = [12, 6]

In [82]:
C_q

array([[80, 80,  5],
       [80, 80,  5],
       [80, 80,  5],
       [80, 80,  5]])

In [80]:
[80, 80].extend([5])

## 计算电容矩阵
节点顺序为比特、coupler I型、coupler II型。。。

In [138]:
types_c = len(C_qc)
n_qi = len(C_qc[0])  # 比特的岛的个数，默认所有比特全同
n_ci_list = [len(C_qc[i][0])
             for i in range(len(C_qc))]  # 每种类型的coupler的岛的个数

N_q = n_q**2 * n_qi
N_c = 2 * n_q * (n_q - 1) * sum(n_ci_list)
# 每类coupler的第一个coupler的节点编号
c_start_index_list = [
    N_q + 2 * n_q * (n_q - 1) * sum(n_ci_list[:j])
    for j in range(len(n_ci_list))
]

C_arr_ori = np.matlib.zeros((N_q + N_c, N_q + N_c))
i = 0
row = i % n_q
column = i // n_q

q_i_index_list = range(n_qi * i, n_qi * (i + 1))

q_i_index_list1 = slice(n_qi * i, n_qi * (i + 1))

if row < n_q - 1:
    # 当前比特的下方比特的不同岛的节点编号
    q_j_index_list = range(n_qi * (i + n_q),
                                n_qi * (i + 1 + n_q))
    
    q_j_index_list1 = slice(n_qi * (i + n_q),
                                n_qi * (i + 1 + n_q))
    C_arr_ori[q_i_index_list, :][:, q_j_index_list] = -C_qq
    print(C_arr_ori[q_i_index_list, :][:, q_j_index_list])
    # 当前比特的下方coupler的不同类型不同岛的节点编号
    c_j_index = row * (2 * n_q -
                       1) + n_q - 1 + column  # 该coupler在本类coupler中的编号

[[0. 0.]
 [0. 0.]]


In [141]:
C_arr_ori[q_i_index_list, q_j_index_list] = -C_qq[0]
C_arr_ori[q_i_index_list, q_j_index_list]

matrix([[-0.5, -0.5]])

In [140]:
q_i_index_list

range(0, 2)

In [128]:
C_arr_ori[q_i_index_list1, q_j_index_list1] = -C_qq
C_arr_ori[q_i_index_list, :][:, q_j_index_list]

matrix([[-0.5, -0.5],
        [-0.5, -0.5]])

In [125]:
C_arr_ori[q_i_index_list, :][:, q_j_index_list]

matrix([[0., 0.],
        [0., 0.]])

In [64]:
slice(n_qi * (i + n_q), n_qi * (i + 1 + n_q))

TypeError: 'slice' object is not iterable

In [150]:
a = np.zeros((3,3))
a[0:2,0:1] = np.ones((2,1))
a

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [152]:
a

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [133]:
a = np.zeros((3,3))
a[[0,1],:][:,[0,1]] = np.ones((2,2))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [411]:
def C_matrix_generate(shape_q, C_q, C_c, C_qc):
    row_max = shape_q[0]
    column_max = shape_q[1]
    n_qi = len(C_qc[0])  # 比特的岛的个数，默认所有比特全同
    n_ci_list = [len(C_qc[i][0]) for i in range(len(C_qc))]  # 每种类型的coupler的岛的个数

    N_q = np.prod(shape_q) * n_qi
    N_c = (2 * row_max * column_max - row_max - column_max) * sum(n_ci_list)
    # 每类coupler的第一个coupler的节点编号
    c_start_index_list = [
        N_q +
        (2 * row_max * column_max - row_max - column_max) * sum(n_ci_list[:j])
        for j in range(len(n_ci_list))
    ]

    C_arr_ori = np.matlib.zeros((N_q + N_c, N_q + N_c))
    C_list = range(N_q + N_c)
    for i in range(row_max * column_max):
        row = i // column_max
        column = i % column_max

        # 当前比特的不同岛的节点编号
        q_i_index_slice = slice(n_qi * i, n_qi * (i + 1))
        q_i_index_list = C_list[q_i_index_slice]

        if row < row_max - 1:
            # 当前比特的下方比特的不同岛的节点编号
            q_j_index_slice = slice(n_qi * (i + column_max),
                                    n_qi * (i + 1 + column_max))
            q_j_index_list = C_list[q_j_index_slice]

            C_arr_ori[q_i_index_slice, q_j_index_slice] = -C_qq

            # 当前比特的下方coupler的不同类型不同岛的节点编号
            c_j_index = row * (
                2 * column_max -
                1) + column_max - 1 + column  # 该coupler在本类coupler中的编号

            for j, c_start_index in enumerate(c_start_index_list):

                c_j_index_slice = slice(
                    c_start_index + n_ci_list[j] * c_j_index,
                    c_start_index + n_ci_list[j] * (c_j_index + 1))
                c_j_index_list = C_list[c_j_index_slice]

                # 当前比特对下方j类coupler
                C_arr_ori[q_i_index_slice, c_j_index_slice] = -C_qc[j]
                # 下方比特对下方j类coupler
                C_arr_ori[q_j_index_slice, c_j_index_slice] = -C_qc[j]
                # 设置下方coupler自电容
                if n_ci_list[j] == 1:
                    C_arr_ori[c_j_index_list, c_j_index_list] = C_c[j]  # 设置岛对地电容
                else:
                    C_arr_ori[c_j_index_list,
                              c_j_index_list] = C_c[j][:-1]  # 设置岛对地电容
                    C_arr_ori[c_j_index_list[0], c_j_index_list[-1]] = -C_c[j][-1]

        if column < column_max - 1:
            # 当前比特的右方比特的不同岛的节点编号
            q_j_index_slice = slice(n_qi * (i + 1), n_qi * (i + 2))
            q_j_index_list = C_list[q_j_index_slice]

            C_arr_ori[q_i_index_slice, q_j_index_slice] = -C_qq
            # 当前比特的右方coupler的不同类型不同岛的节点编号
            c_j_index = row * (2 * column_max -
                               1) + column  # 该coupler在本类coupler中的编号

            for j, c_start_index in enumerate(c_start_index_list):

                c_j_index_slice = slice(
                    c_start_index + n_ci_list[j] * c_j_index,
                    c_start_index + n_ci_list[j] * (c_j_index + 1))

                c_j_index_list = C_list[c_j_index_slice]
                # 当前比特对右方j类coupler
                C_arr_ori[q_i_index_slice, c_j_index_slice] = -C_qc[j]
                # 右方比特对右方j类coupler
                C_arr_ori[q_j_index_slice, c_j_index_slice] = -C_qc[j]
                # 设置右方coupler自电容
                if n_ci_list[j] == 1:
                    C_arr_ori[c_j_index_list, c_j_index_list] = C_c[j]  # 设置岛对地电容
                else:
                    C_arr_ori[c_j_index_list,
                              c_j_index_list] = C_c[j][:-1]  # 设置岛对地电容
                    C_arr_ori[c_j_index_list[0], c_j_index_list[-1]] = -C_c[j][-1]

        # 设置比特自电容
        nq_around = 0  # 比特周围的比特数
        if row < row_max - 1:
            nq_around += 1
        if row > 0:
            nq_around += 1
        if column < column_max - 1:
            nq_around += 1
        if column > 0:
            nq_around += 1

        if n_qi == 1:
            C_arr_ori[q_i_index_list, q_i_index_list] = C_q[nq_around - 1]
        else:
            C_arr_ori[q_i_index_list, q_i_index_list] = C_q[nq_around - 1][:-1]
            C_arr_ori[q_i_index_list[0],
                      q_i_index_list[-1]] = -C_q[nq_around - 1][-1]

    # 设置下三角区域元素
    C_down = C_arr_ori.T
    C_arr_ori = C_arr_ori + C_down
    C_arr_ori[C_list, C_list] = C_arr_ori[C_list, C_list] / 2

    # 把非对角元加到对角元上
    C_arr_ori[C_list,
              C_list] = 2 * C_arr_ori[C_list, C_list] - C_arr_ori.sum(axis=0)

    return C_arr_ori

In [412]:
def C_energy(shape_q, C_para_dic, trans_matrix_dic):
    C_q = C_para_dic['C_q']
    C_c = C_para_dic['C_c']
    C_qc = C_para_dic['C_qc']
    C_qq = C_para_dic['C_qq']
    row_max = shape_q[0]
    column_max = shape_q[1]
    C_arr_ori = C_matrix_generate(shape_q, C_q, C_c, C_qc)

    n_qi = len(C_qc[0])  # 比特的岛的个数，默认所有比特全同
    n_ci_list = [len(C_qc[i][0]) for i in range(len(C_qc))]  # 每种类型的coupler的岛的个数

    n_q = np.prod(shape_q)
    N_q = n_q * n_qi
    n_c = (2 * row_max * column_max - row_max - column_max)
    N_c = n_c * sum(n_ci_list)
    trans_matrix_add = []

    node_each_list = [n_q] + [n_c] * len(n_ci_list)
    node_list = [sum(node_each_list[:i + 1]) for i in range(len(node_each_list))]

    matrix_list = [trans_matrix_dic['matrix']['q']
                   ] + trans_matrix_dic['matrix']['c']

    for i in range(node_list[-1]):
        node_list_new = node_list + [i]
        node_list_new.sort()
        type_i = node_list_new.index(i)
        trans_matrix_add.append(matrix_list[type_i])
    trans_matrix_all = np.matrix(block_diag(*trans_matrix_add))

    C_arr_ori_trans = np.linalg.inv(
        trans_matrix_all).T * C_arr_ori * np.linalg.inv(trans_matrix_all)

    C_arr_ori_inv = np.linalg.inv(C_arr_ori_trans)

    c_start_index_list = [
        N_q + n_c * sum(n_ci_list[:j]) for j in range(len(n_ci_list))
    ]
    start_index_list = [0] + c_start_index_list

    reserve_index = [trans_matrix_dic['reserve index']['q']
                     ] + trans_matrix_dic['reserve index']['c']
    n_i_list = [n_qi] + n_ci_list

    reserve_index_all = []

    for i in range(1, len(start_index_list)):
        reserve_index_type = [
            list(
                range(start_index_list[i - 1] + reserve_index_i,
                      start_index_list[i], n_i_list[i - 1]))
            for reserve_index_i in reserve_index[i - 1]
            if reserve_index_i is not None
        ]

        reserve_index_all.extend(*reserve_index_type)

    reserve_index_all.sort()

    n_list = range(n_q + n_c)

    C_energy_matrix = C_arr_ori_inv[reserve_index_all, :][:, reserve_index_all]

    C_energy_matrix = constants.e**2 / constants.h * C_energy_matrix * 1e15 / 1e9*1e3 # 单位MHz
    C_energy_matrix[n_list, n_list] = C_energy_matrix[n_list, n_list] / 2
    C_energy_matrix.round(2)
    
    return C_arr_ori, C_energy_matrix

In [363]:
C_para_dic = {
    'C_q': np.array([69.5, 57.85, 46.4, 34.9]),
    'C_c': np.array([117.5, 125]),
    'C_qc': np.array([[[6.33]], [[5.7]]]),
    'C_qq': np.array([[0]])
}

shape_q = [4, 4]

trans_matrix_dic = {
    'matrix': {
        'q': np.array([[1]]),
        'c': [np.array([[1]]), np.array([[1]])]
    },
    'reserve index': {
        'q': [0],
        'c': [[0], None]
    }
}

In [458]:
29.77+5.91

35.68

In [459]:
C_para_dic = {
    'C_q': np.array([70.5, 58.31, 47.05, 35.68]),
    'C_c': np.array([117.9, 125.8]),
    'C_qc': np.array([[[6.099]], [[5.62]]]),
    'C_qq': np.array([[0] ])
}

shape_q = [12, 6]

trans_matrix_dic = {
    'matrix': {
        'q': np.array([[1]]),
        'c': [np.array([[1]]), np.array([[1]])]
    },
    'reserve index': {
        'q': [0],
        'c': [[0], None]
    }
}

In [460]:
C_arr_ori, C_energy_matrix = C_energy(shape_q, C_para_dic, trans_matrix_dic)

In [408]:
##
C_q = C_para_dic['C_q']
C_c = C_para_dic['C_c']
C_qc = C_para_dic['C_qc']
C_qq = C_para_dic['C_qq']
row_max = shape_q[0]
column_max = shape_q[1]
n_qi = len(C_qc[0])  # 比特的岛的个数，默认所有比特全同
n_ci_list = [len(C_qc[i][0]) for i in range(len(C_qc))]  # 每种类型的coupler的岛的个数

N_q = np.prod(shape_q) * n_qi
N_c = (2 * row_max * column_max - row_max - column_max) * sum(n_ci_list)
# 每类coupler的第一个coupler的节点编号
c_start_index_list = [
    N_q +
    (2 * row_max * column_max - row_max - column_max) * sum(n_ci_list[:j])
    for j in range(len(n_ci_list))
]

C_arr_ori = np.matlib.zeros((N_q + N_c, N_q + N_c))
C_list = range(N_q + N_c)
for i in range(row_max * column_max):
    row = i // column_max
    column = i % column_max

    # 当前比特的不同岛的节点编号
    q_i_index_slice = slice(n_qi * i, n_qi * (i + 1))
    q_i_index_list = C_list[q_i_index_slice]

    if row < row_max - 1:
        # 当前比特的下方比特的不同岛的节点编号
        q_j_index_slice = slice(n_qi * (i + column_max),
                                n_qi * (i + 1 + column_max))
        q_j_index_list = C_list[q_j_index_slice]

        C_arr_ori[q_i_index_slice, q_j_index_slice] = -C_qq

        # 当前比特的下方coupler的不同类型不同岛的节点编号
        c_j_index = row * (
            2 * column_max -
            1) + column_max - 1 + column  # 该coupler在本类coupler中的编号

        for j, c_start_index in enumerate(c_start_index_list):

            c_j_index_slice = slice(
                c_start_index + n_ci_list[j] * c_j_index,
                c_start_index + n_ci_list[j] * (c_j_index + 1))
            c_j_index_list = C_list[c_j_index_slice]

            # 当前比特对下方j类coupler
            C_arr_ori[q_i_index_slice, c_j_index_slice] = -C_qc[j]
            # 下方比特对下方j类coupler
            C_arr_ori[q_j_index_slice, c_j_index_slice] = -C_qc[j]
            # 设置下方coupler自电容
            if n_ci_list[j] == 1:
                C_arr_ori[c_j_index_list, c_j_index_list] = C_c[j]  # 设置岛对地电容
            else:
                C_arr_ori[c_j_index_list,
                          c_j_index_list] = C_c[j][:-1]  # 设置岛对地电容
                C_arr_ori[c_j_index_list[0], c_j_index_list[-1]] = -C_c[j][-1]

    if column < column_max - 1:
        # 当前比特的右方比特的不同岛的节点编号
        q_j_index_slice = slice(n_qi * (i + 1), n_qi * (i + 2))
        q_j_index_list = C_list[q_j_index_slice]

        C_arr_ori[q_i_index_slice, q_j_index_slice] = -C_qq
        # 当前比特的右方coupler的不同类型不同岛的节点编号
        c_j_index = row * (2 * column_max -
                           1) + column  # 该coupler在本类coupler中的编号

        for j, c_start_index in enumerate(c_start_index_list):

            c_j_index_slice = slice(
                c_start_index + n_ci_list[j] * c_j_index,
                c_start_index + n_ci_list[j] * (c_j_index + 1))

            c_j_index_list = C_list[c_j_index_slice]
            # 当前比特对右方j类coupler
            C_arr_ori[q_i_index_slice, c_j_index_slice] = -C_qc[j]
            # 右方比特对右方j类coupler
            C_arr_ori[q_j_index_slice, c_j_index_slice] = -C_qc[j]
            # 设置右方coupler自电容
            if n_ci_list[j] == 1:
                C_arr_ori[c_j_index_list, c_j_index_list] = C_c[j]  # 设置岛对地电容
            else:
                C_arr_ori[c_j_index_list,
                          c_j_index_list] = C_c[j][:-1]  # 设置岛对地电容
                C_arr_ori[c_j_index_list[0], c_j_index_list[-1]] = -C_c[j][-1]

    # 设置比特自电容
    nq_around = 0  # 比特周围的比特数
    if row < row_max - 1:
        nq_around += 1
    if row > 0:
        nq_around += 1
    if column < column_max - 1:
        nq_around += 1
    if column > 0:
        nq_around += 1

    if n_qi == 1:
        C_arr_ori[q_i_index_list, q_i_index_list] = C_q[nq_around - 1]
    else:
        C_arr_ori[q_i_index_list, q_i_index_list] = C_q[nq_around - 1][:-1]
        C_arr_ori[q_i_index_list[0],
                  q_i_index_list[-1]] = -C_q[nq_around - 1][-1]

# 设置下三角区域元素
C_down = C_arr_ori.T
C_arr_ori = C_arr_ori + C_down
C_arr_ori[C_list, C_list] = C_arr_ori[C_list, C_list] / 2

# 把非对角元加到对角元上
C_arr_ori[C_list,
          C_list] = 2 * C_arr_ori[C_list, C_list] - C_arr_ori.sum(axis=0)

In [ ]:
##
n_qi = len(C_qc[0])  # 比特的岛的个数，默认所有比特全同
n_ci_list = [len(C_qc[i][0]) for i in range(len(C_qc))]  # 每种类型的coupler的岛的个数

n_q = np.prod(shape_q)
N_q = n_q * n_qi
n_c = (2 * row_max * column_max - row_max - column_max)
N_c = n_c * sum(n_ci_list)
trans_matrix_add = []

node_each_list = [n_q] + [n_c] * len(n_ci_list)
node_list = [sum(node_each_list[:i + 1]) for i in range(len(node_each_list))]

matrix_list = [trans_matrix_dic['matrix']['q']
               ] + trans_matrix_dic['matrix']['c']

for i in range(node_list[-1]):
    node_list_new = node_list + [i]
    node_list_new.sort()
    type_i = node_list_new.index(i)
    trans_matrix_add.append(matrix_list[type_i])
trans_matrix_all = np.matrix(block_diag(*trans_matrix_add))

C_arr_ori_trans = np.linalg.inv(
    trans_matrix_all).T * C_arr_ori * np.linalg.inv(trans_matrix_all)

C_arr_ori_inv = np.linalg.inv(C_arr_ori_trans)

c_start_index_list = [
    N_q + n_c * sum(n_ci_list[:j]) for j in range(len(n_ci_list))
]
start_index_list = [0] + c_start_index_list

reserve_index = [trans_matrix_dic['reserve index']['q']
                 ] + trans_matrix_dic['reserve index']['c']
n_i_list = [n_qi] + n_ci_list

reserve_index_all = []

for i in range(1, len(start_index_list)):
    reserve_index_type = [
        list(
            range(start_index_list[i - 1] + reserve_index_i,
                  start_index_list[i], n_i_list[i - 1]))
        for reserve_index_i in reserve_index[i - 1]
        if reserve_index_i is not None
    ]

    reserve_index_all.extend(*reserve_index_type)

reserve_index_all.sort()

n_list = range(n_q + n_c)

C_energy_matrix = C_arr_ori_inv[reserve_index_all, :][:, reserve_index_all]

C_energy_matrix = constants.e**2 / constants.h * C_energy_matrix * 1e15 / 1e9*1e3 # 单位MHz
C_energy_matrix[n_list, n_list] = C_energy_matrix[n_list, n_list] / 2
C_energy_matrix.round(2)

In [319]:
0.031*1/(5.24/5*7.15/7)**(1/2)

0.02996243132452808

In [318]:
0.0034*1/(5.24/5*5.24/5)**(1/2)

0.003244274809160305

In [468]:
pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',200)
pd.DataFrame(C_energy_matrix)

0             1             2             3             4    \
0    2.400021e+02  3.073519e+00  1.968089e-02  1.260293e-04  8.070795e-07   
1    3.073519e+00  2.401827e+02  3.075833e+00  1.969571e-02  1.261242e-04   
2    1.968089e-02  3.075833e+00  2.401827e+02  3.075833e+00  1.969571e-02   
3    1.260293e-04  1.969571e-02  3.075833e+00  2.401827e+02  3.075833e+00   
4    8.070795e-07  1.261242e-04  1.969571e-02  3.075833e+00  2.401827e+02   
5    5.164783e-09  8.070795e-07  1.260293e-04  1.968089e-02  3.073519e+00   
6    3.073519e+00  3.941513e-02  3.790183e-04  3.239599e-06  2.595944e-08   
7    3.944202e-02  3.082483e+00  3.951439e-02  3.799226e-04  3.247113e-06   
8    3.793631e-04  3.951439e-02  3.082484e+00  3.951440e-02  3.799226e-04   
9    3.242914e-06  3.799226e-04  3.951440e-02  3.082484e+00  3.951439e-02   
10   2.598778e-08  3.247113e-06  3.799226e-04  3.951439e-02  3.082483e+00   
11   1.994774e-10  2.595944e-08  3.239599e-06  3.790183e-04  3.941513e-02   
12   1.968089e-02  3.790183e-04  4.862851e-06  5.198280e-08  5.000806e-10   
13   3.793631e-04  1.978178e-02  3.804748e-04  4.879102e-06  5.214234e-08   
14   4.868379e-06  3.804748e-04  1.978179e-02  3.804749e-04  4.879102e-06   
15   5.204660e-08  4.879102e-06  3.804749e-04  1.978179e-02  3.804748e-04   
16   5.007170e-10  5.214234e-08  4.879102e-06  3.804748e-04  1.978178e-02   
17   4.483361e-12  5.000806e-10  5.198280e-08  4.862851e-06  3.790183e-04   
18   1.260293e-04  3.239599e-06  5.198280e-08  6.670563e-10  7.488744e-12   
19   3.242914e-06  1.269596e-04  3.256016e-06  5.219947e-08  6.695154e-10   
20   5.204660e-08  3.256017e-06  1.269598e-04  3.256019e-06  5.219948e-08   
21   6.679203e-10  5.219948e-08  3.256019e-06  1.269598e-04  3.256017e-06   
22   7.498661e-12  6.695154e-10  5.219947e-08  3.256016e-06  1.269596e-04   
23   7.671984e-14  7.488744e-12  6.670563e-10  5.198280e-08  3.239599e-06   
24   8.070795e-07  2.595944e-08  5.000807e-10  7.488746e-12  9.610248e-14   
25   2.598778e-08  8.148941e-07  2.612199e-08  5.025592e-10  7.520716e-12   
26   5.007171e-10  2.612200e-08  8.148964e-07  2.612202e-08  5.025593e-10   
27   7.498663e-12  5.025593e-10  2.612202e-08  8.148964e-07  2.612200e-08   
28   9.623161e-14  7.520716e-12  5.025592e-10  2.612199e-08  8.148941e-07   
29   1.107382e-15  9.610248e-14  7.488746e-12  5.000807e-10  2.595944e-08   
30   5.168674e-09  1.996998e-10  4.489987e-12  7.686119e-14  1.109827e-15   
31   1.999269e-10  5.230851e-09  2.011871e-10  4.515723e-12  7.723331e-14   
32   4.495817e-12  2.011871e-10  5.230875e-09  2.011874e-10  4.515724e-12   
33   7.696410e-14  4.515724e-12  2.011874e-10  5.230875e-09  2.011871e-10   
34   1.111328e-15  7.723331e-14  4.515723e-12  2.011871e-10  5.230851e-09   
35   1.420596e-17  1.109827e-15  7.686119e-14  4.489987e-12  1.996998e-10   
36   3.310244e-11  1.493602e-12  3.839344e-14  7.395395e-16  1.186663e-17   
37   1.495348e-12  3.357987e-11  1.506498e-12  3.864319e-14  7.435413e-16   
38   3.844392e-14  1.506498e-12  3.358010e-11  1.506502e-12  3.864320e-14   
39   7.405356e-16  3.864320e-14  1.506502e-12  3.358010e-11  1.506498e-12   
40   1.188272e-17  7.435413e-16  3.864319e-14  1.506498e-12  3.357987e-11   
41   1.670399e-19  1.186663e-17  7.395395e-16  3.839344e-14  1.493602e-12   
42   2.120113e-13  1.094327e-14  3.165743e-16  6.776716e-18  1.196276e-19   
43   1.095634e-14  2.155862e-13  1.105082e-14  3.188788e-16  6.817255e-18   
44   3.169939e-16  1.105082e-14  2.155884e-13  1.105086e-14  3.188789e-16   
45   6.785877e-18  3.188789e-16  1.105086e-14  2.155884e-13  1.105082e-14   
46   1.197901e-19  6.817255e-18  3.188788e-16  1.105082e-14  2.155862e-13   
47   1.836500e-21  1.196276e-19  6.776716e-18  3.165743e-16  1.094327e-14   
48   1.357926e-15  7.892802e-17  2.537834e-18  5.976894e-20  1.151131e-21   
49   7.902375e-17  1.384198e-15  7.979861e-17  2.558284e-18  6.016073e-20   
50   2.541217e-18  7.979863e-17  1.384218e-15  7.979900e-17  2.558284e-18   
51   5.984

In [464]:
C_energy_matrix[100,100]

149.95427036469633

In [471]:
q_index = 7
c_index = 9
rho = C_energy_matrix[q_index,c_index]/(4*(C_energy_matrix[q_index,q_index]*C_energy_matrix[c_index,c_index])**(1/2))

In [473]:
rho*(5.24/5*5.24/5)**(1/2)*np.sqrt(5*5)

0.00010789340284110163

In [438]:
if column < n_q - 1:
    # 当前比特的右方比特的不同岛的节点编号
    q_j_index_list = slice(n_qi * (i + 1), n_qi * (i + 2))
    C_arr_ori[q_i_index_list, q_j_index_list] = C_qq
    # 当前比特的下方coupler的不同类型不同岛的节点编号
    c_j_index = row * (2 * n_q - 1) + column  # 该coupler在本类coupler中的编号

    for j, c_start_index in enumerate(c_start_index_list):

        c_j_index_list = slice(
            c_start_index + n_ci_list[j] * c_j_index,
            c_start_index + n_ci_list[j] * (c_j_index + 1))
        # 当前比特对下方j类coupler
        C_arr_ori[q_i_index_list, c_j_index_list] = C_qc[j]
        # 下方比特对下方j类coupler
        C_arr_ori[q_j_index_list, c_j_index_list] = C_qc[j]

In [69]:
C_arr_ori[q_i_index_list,:][:,q_i_index_list]

matrix([[0., 0.],
        [0., 0.]])

In [32]:
types_c = len(C_qc)
n_qi = len(C_qc[0])
n_ci = len(C_qc[0][0])

N_q = n_q**2 * n_qi
N_c = 2 * n_q * (n_q - 1) * n_ci * types_c

C_arr_ori = np.matlib.zeros((N_q + N_c, N_q + N_c))

    

In [44]:
i= 5
row = i % n_q
column = i // n_q

In [46]:
row*(2*n_q-1)+n_q-1+column

11

In [42]:
C_arr_ori[n_qi * i:n_qi * (i + 1), n_qi * i - n_q:n_qi * (i + 1) - n_q] = C_qq
C_arr_ori[range(5,6), n_qi * i - n_q:n_qi * (i + 1) - n_q]

matrix([[5.]])

In [ ]:
np.set_printoptions(threshold=np.inf)
C_arr_ori

In [467]:
10.833 - 1.666


9.167